### PR TITLE
server: simplify logic for accepting/rejecting external API requests

### LINKED ISSUE #284: Updates to a VM controller's `lifecycle_stage` are race-prone
Passing `Run` to `VmController::put_state` is supposed to be a no-op if the instance is already active: https://github.com/oxidecomputer/propolis/blob/584eac234598b90e25f315a73cef1271e4eac398/bin/propolis-server/src/lib/vm.rs#L764-L790

The current synchronization between the controller and state worker creates a small window where the VM is already running but the lifecycle stage is not updated yet, allowing a `Start` request to be queued to (and--incorrectly--processed by) the state worker even though the VM is already running. This part of the state worker logic needs to be reworked a bit and (hopefully) simplified.

### LINKED ISSUE #341: Requests to migrate into an instance are not idempotent
https://github.com/oxidecomputer/propolis/blob/d9434e54f8695b2c0e2f4f47c98c11095479e0e1/bin/propolis-server/src/lib/vm/mod.rs#L779-L800

The first request to migrate into an instance sets the lifecycle stage to "MigratePending" and so blocks future requests to become a migration target. The migration saga will generally assume these requests are idempotent, since it has a step that issues them.

I have some local changes drafted that should help address this.

### PR DESCRIPTION
**Pull request by gjcolombo**
**Reviewer note:** This might be a little more digestible when reviewed as a series of commits.

---

Simplify the propolis-server VM controller's logic for deciding what external API requests to accept or reject. The commit descriptions in this PR's commits explain the changes in more detail, but to summarize:

Currently, the propolis-server VM controller maintains some high-level state (a "lifecycle stage" and accompanying flags) and matches on that state to decide how to handle incoming external API requests. This code has some idempotency bugs (#284, #341), is hard to read, and requires a bunch of extra upcalls in the state driver -> VM controller interface (because the state can change both when requests are queued and when they are completed).

To fix this, introduce an "external request queue" module that serves the same function as the old lifecycle stage code. Instead of keeping track of VM states, the queue receives requests and VM state changes as inputs and stores as state the dispositions it should give new external requests as they come in. The queue is directly shared by the VM controller and state driver so that the latter doesn't have to call up to the former to get at the queue.

Also rearrange some state driver code for readability (move logic out of the top-level dispatch loop into callees).

After this some follow-up work is required to make sure we publish all the right states at the right times (and that publishing the "Failed" state has the correct semantics), especially when completing migrations.

Fixes #284. Fixes #341.

### CODE REVIEW

File: bin/propolis-server/src/lib/vm/request_queue.rs [hunk 1]
```diff
@@ -0,0 +1,358 @@
...
+    #[error(
+        "The requested operation cannot be performed on a migration source"
+    )]
+    InvalidRequestForMigrationSource,
+
+    #[error("The instance is preparing to stop")]
+    HaltPending,
+
+    #[error("The instance failed to start or halted due to a failure")]
+    InstanceFailed,
```
Comment (jordanhendricks) [inline bin/propolis-server/src/lib/vm/request_queue.rs:110]: a bit nitty, but I think I would prefer if these errors are a bit less verbose, such as removing The/A at the beginning

File: bin/propolis-server/src/lib/vm/request_queue.rs [hunk 2]
```diff
@@ -0,0 +1,358 @@
...
+}
+
+/// The possible methods of handling a request to queue a state change.
+#[derive(Copy, Clone, Debug)]
+enum RequestDisposition {
+    /// Put the state change on the queue.
+    Enqueue,
+
+    /// Drop the state change silently.
```
Comment (jordanhendricks) [inline bin/propolis-server/src/lib/vm/request_queue.rs:119]: I know this is mentioned elsewhere, but I would mention this disposition exists for idempotency purposes here.

File: bin/propolis-server/src/lib/vm/request_queue.rs [hunk 3]
```diff
@@ -0,0 +1,358 @@
...
+        };
+
+        info!(&self.log, "queuing external request";
+              "request" => ?request,
+              "disposition" => ?disposition);
+
+        // At this point the request will be queued. Queuing some requests
+        // logically forecloses on other kinds of requests. Update the
+        // dispositions of these requests, then queue the request.
+        match request {
```
Comment (jordanhendricks) [inline bin/propolis-server/src/lib/vm/request_queue.rs:210]: When reading this piece of this method, I found myself wanting a table helping me translate the request and the set of allowed states after we enqueue it. This was particularly true where the resulting disposition of a request type would be implicit.

What would you think about matching on the request and returning from the `match` the AllowedRequests struct that would be associated with it? That might make it easier to grok reading this, since you can walk up to the function and quickly glean what the resulting dispositions will be.

For example, for the `MigrateAsTarget` case, something like:
```
let allowed_requests = match request {
    ExternalRequest::MigrateAsTarget { .. } => {
        AllowedRequests {
            migrate_as_target: Disposition::Ignore,
            start: Disposition::Ignore,
            migrate_as_source: Disposition::Deny(DenyReason::MigrateTargetInProgress),
            reboot: Disposition::Deny(DenyReason::MigrateTargetInProgress),
            stop: Disposition::Enqueue,
        }
    },

// ... handle other request types

};
```

File: bin/propolis-server/src/lib/vm/request_queue.rs [hunk 4]
```diff
@@ -0,0 +1,358 @@
...
+        info!(self.log, "Instance has failed, denying all actions");
+        self.allowed.migrate_as_target =
+            RequestDisposition::Deny(RequestDeniedReason::InstanceFailed);
+        self.allowed.start =
+            RequestDisposition::Deny(RequestDeniedReason::InstanceFailed);
+        self.allowed.migrate_as_source =
+            RequestDisposition::Deny(RequestDeniedReason::InstanceFailed);
+        self.allowed.reboot =
+            RequestDisposition::Deny(RequestDeniedReason::InstanceFailed);
+    }
```
Comment (jordanhendricks) [inline bin/propolis-server/src/lib/vm/request_queue.rs:331]: We could also do something similar here -- return a new AllowedRequests struct to wholesale replace the existing one.

File: bin/propolis-server/src/lib/vm/request_queue.rs [hunk 5]
```diff
@@ -0,0 +1,358 @@
...
+
+    /// Indicates whether the queue would allow a request to migrate into this
+    /// instance. This can be used to avoid setting up migration tasks for
+    /// requests that will ultimately be denied.
+    pub fn migrate_as_target_allowed(&self) -> Result<(), RequestDeniedReason> {
+        match self.allowed.migrate_as_target {
+            RequestDisposition::Enqueue => Ok(()),
+            RequestDisposition::Ignore => {
+                panic!("requests to migrate as target should not be ignored")
```
Comment (jordanhendricks) [inline bin/propolis-server/src/lib/vm/request_queue.rs:340]: this feels more like an `assert!`?

File: bin/propolis-server/src/lib/vm/request_queue.rs [hunk 6]
```diff
@@ -0,0 +1,358 @@
...
+    }
+
+    /// Indicates whether the queue would allow a request to migrate out of this
+    /// instance. This can be used to avoid setting up migration tasks for
+    /// requests that will ultimately be denied.
+    pub fn migrate_as_source_allowed(&self) -> Result<(), RequestDeniedReason> {
+        match self.allowed.migrate_as_source {
+            RequestDisposition::Enqueue => Ok(()),
+            RequestDisposition::Ignore => {
+                panic!("requests to migrate as source should not be ignored")
```
Comment (jordanhendricks) [inline bin/propolis-server/src/lib/vm/request_queue.rs:353]: same here

File: bin/propolis-server/src/lib/vm/state_driver.rs [hunk 7]
```diff
@@ -124,17 +128,9 @@ where
...
         loop {
-            let event = self.controller.wait_for_next_event();
-            let outcome = self.handle_event(event, &mut next_lifecycle);
-
-            if let Some(next_lifecycle) = next_lifecycle.take() {
-                self.controller.set_lifecycle_stage(next_lifecycle);
-            }
-
+            let event = self.shared_state.wait_for_next_event();
+            let outcome = self.handle_event(event);
```
Comment (jordanhendricks) [inline bin/propolis-server/src/lib/vm/state_driver.rs:133]: This pattern is definitely much cleaner than what was here before -- it looks nice!

**Review by jordanhendricks — COMMENTED** [review]
This looks pretty good! I really like how much simpler this makes the event handling to follow. A couple review comments for now.

**Comment by gjcolombo** [comment]
Thanks @jordanhendricks! Commit 20c2a32 should address all the feedback above. I also tacked on some unit tests in 318fbc4 (including one covering some behavior that was incorrect in the original change...).

File: bin/propolis-server/src/lib/vm/request_queue.rs (hunk 3 above)
Comment (gjcolombo) [reply bin/propolis-server/src/lib/vm/request_queue.rs]: I really like the way this worked out--thanks for suggesting it!

**Comment by gjcolombo** [comment]
Hmm, that vmm handle leak in the PHD run is new... Will look into it.

**Comment by gjcolombo** [comment]
> Hmm, that vmm handle leak in the PHD run is new... Will look into it.

This is a regression in the last batch of changes. Working on a fix.

**Comment by gjcolombo** [comment]
The bug was a copy-and-paste error. Transitioning to a Failed state (which we now do in this PR when migration in fails) used to preserve the last disposition for requests to stop, which (in the relevant PHD tests) was Enqueue. 20c2a32 broke this and changed it to Ignore. e0d8da2 fixes the problem and adds a unit test. With any luck the PHD run will come out clean this time.

File: bin/propolis-server/src/lib/vm/request_queue.rs [hunk 8]
```diff
@@ -0,0 +1,549 @@
...
+    /// instance. This can be used to avoid setting up migration tasks for
+    /// requests that will ultimately be denied.
+    ///
+    /// # Return value
+    ///
+    /// - `Ok(true)` if the request will be queued.
+    /// - `Ok(false)` if the request is allowed for idempotency reasons but will
+    ///   not be queued.
+    /// - `Err` if the request is forbidden.
+    pub fn migrate_as_target_will_enqueue(
```
Comment (jordanhendricks) [inline bin/propolis-server/src/lib/vm/request_queue.rs:245]: Thanks for this -- I like this naming better than the original version.

**Review by jordanhendricks — APPROVED** [review]

File: bin/propolis-server/src/lib/vm/request_queue.rs (hunk 3 above)
Comment (jordanhendricks) [reply bin/propolis-server/src/lib/vm/request_queue.rs]: glad to hear it! I like the way the new version looks, too.
