### PR TITLE
Configure exitcode for reboot/halt on standalone

### LINKED ISSUE #557: standalone: option for process exit on guest reboot with stable exit status
In order to assist with the use of **propolis-standalone** for certain automated tests and jobs, it would help to have a new command line flag or configuration file property that would make the hypervisor process exit if the guest tries to reboot, like we do today when the guest requests power off, rather than allowing the reboot to proceed.  It would be good also to be able to have a particular exit status for a guest reboot (e.g., exit 10) to make it easy to determine when one has occurred, versus the guest powering itself off (presumably exit 0) or the hypervisor crashing (presumably exit 1 or abort or whatever today).

### PR DESCRIPTION
**Pull request by pfmooney**
Fixes #557

### CODE REVIEW

File: bin/propolis-standalone/src/main.rs [hunk 1]
```diff
@@ -1058,6 +1070,6 @@ fn main() -> anyhow::Result<()> {
     );
 
     // wait for instance to be destroyed
-    inst.wait_destroyed();
-    Ok(())
+    let code = inst.wait_destroyed();
+    std::process::exit(code);
```
Comment (jclulow) [inline bin/propolis-standalone/src/main.rs:1074]: Does the move to an explicit exit here change the behaviour, because we are now not actually returning from **main()** any more?  In particular, I wonder if we previously would have called a bunch of **Drop** routines and now we're not doing that...

File: bin/propolis-standalone/src/main.rs [hunk 2]
```diff
@@ -404,8 +406,17 @@ impl Instance {
                     for mut vcpu_ctrl in guard.vcpu_tasks.drain(..) {
                         vcpu_ctrl.exit();
                     }
+                    if guard.exit_code.is_none() {
+                        guard.exit_code = Some(inner.config.main.exit_on_halt);
+                    }
                 }
                 State::Reset => {
+                    if let Some(code) = inner.config.main.exit_on_reboot {
+                        guard.exit_code = Some(code);
```
Comment (jclulow) [inline bin/propolis-standalone/src/main.rs:415]: Should we do the same **is_none()** check you're doing on 409 for the **Halt** version?

**Review by jclulow — COMMENTED** [review]
Thanks for doing this so quickly!  I have a couple of small questions.

File: bin/propolis-standalone/src/main.rs (hunk 1 above)
Comment (pfmooney) [reply bin/propolis-standalone/src/main.rs]: Unless propolis components are spawning tasks which aren't themselves collected on instance destroy, we should be pretty well cleaned up by now.

That said, I've refactored and cleaned up some other bits so we can return an `ExitCode`.

File: bin/propolis-standalone/src/main.rs (hunk 2 above)
Comment (pfmooney) [reply bin/propolis-standalone/src/main.rs:421]: I don't believe it's strictly necessary at this time, but for defense-in-depth purposes, I've added such a check. (In case we add something like exit-on-fault to bail out on a triple-fault or something)

**Review by jclulow — APPROVED** [review]
Huh!  TIL **ExitCode**.  Neat!
